version: '3'

services:
  #frontend: 
  # build: frontend
  # depends_on:
  #   - database
  #   - adminer
  # ports:
  #   - 5173:5173

  backend:
    build: backend
    stdin_open: true
    tty: true
    environment:
      - DB_USER=admin
    ports:
      - 5001:5000
    volumes:
      - ./backend:/backend

  database:
    image: mariadb
    environment:
      MARIADB_ROOT_PASSWORD: example
      MARIADB_USER: admin
      MARIADB_PASSWORD: toto90
      MARIADB_DATABASE: devops_jobs

  adminer:
    image: adminer
    ports:
      - 8080:8080
