version: '3'

services:
  #frontend: 
  #  build: frontend
  #  ports:
  #    - 5173:5173
  #  volumes:
  #   - ./frontend:/frontend

  backend:
    build: backend
    stdin_open: true
    tty: true
    ports:
      - 5001:5000
    volumes:
      - ./backend:/backend

  database:
    image: mariadb
    environment:
      MARIADB_ROOT_PASSWORD: example
      MARIADB_USER: admin@devjobs
      MARIADB_PASSWORD: secretpw
      MARIADB_DATABASE: devjobs

  adminer:
    image: adminer
    ports:
      - 8080:8080