services:
  backend:
    build: backend
    stdin_open: true
    tty: true
    ports:
      - 5000:5000
    volumes:
      - ./backend:/backend
    depends_on:
      - database

  database:
    image: mariadb
    env_file:
      - ./backend/.env
    volumes:
      - ./data/mysql:/var/lib/mysql
    ports:
      - 3306:3306

  adminer:
    image: adminer
    ports:
      - 8080:8080