name: Continuous integration devjobs

on:
  pull_request:
    paths:
      - 'frontend/**'
    branches:
      - main

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run tests in frontend
        run: |
          cd frontend
          npm ci --prefix frontend 
          npm run lint  
          npm run test 
